#include "MainWindow.h"
#include "ScreenItem.h"
#include <QVBoxLayout>
#include <QPushButton>
#include <QToolBar>
#include <QFileDialog>
#include <QMessageBox>
#include <QTextStream>
#include <QDebug>
#include <QProcess>

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
{
    setupUi();
    loadScreens();
}

MainWindow::~MainWindow()
{
}

void MainWindow::setupUi()
{
    setWindowTitle("Horizon - Display Manager");
    resize(800, 600);

    // Central Widget
    QWidget *centralWidget = new QWidget(this);
    setCentralWidget(centralWidget);
    QVBoxLayout *layout = new QVBoxLayout(centralWidget);

    // Graphics View for Monitors
    scene = new QGraphicsScene(this);
    view = new QGraphicsView(scene);
    view->setRenderHint(QPainter::Antialiasing);
    view->setBackgroundBrush(QBrush(QColor(50, 50, 50)));
    layout->addWidget(view);

    // Toolbar
    QToolBar *toolbar = addToolBar("Main Toolbar");
    QAction *reloadAction = toolbar->addAction("Reload");
    QAction *applyAction = toolbar->addAction("Apply");
    QAction *saveAction = toolbar->addAction("Save As...");

    connect(reloadAction, &QAction::triggered, this, &MainWindow::reloadScreens);
    connect(applyAction, &QAction::triggered, this, &MainWindow::applyConfig);
    connect(saveAction, &QAction::triggered, this, &MainWindow::saveConfig);
}

void MainWindow::loadScreens()
{
    scene->clear();
    std::vector<ScreenInfo> screens = m_manager.getScreens();
    
    // Determine bounding rect to center view? For now just place them
    for (const auto &screen : screens) {
        if (!screen.active) continue; // Skip inactive for now
        
        ScreenItem *item = new ScreenItem(screen.name, screen.width, screen.height);
        // Position is scaled by 1/10
        item->setPos(screen.x / 10.0, screen.y / 10.0);
        scene->addItem(item);
    }
}

void MainWindow::reloadScreens()
{
    // Force re-parse
    // XrandrManager logic needs to be stateless or have a reload method?
    // Current implementation: getScreens() calls parse if empty.
    // We should probably force a refresh.
    // Hack: instantiate new manager or make parse public. 
    // Let's just create a new manager or rely on current behavior + clear
    // But XrandrManager stores state.
    // We will assume XrandrManager re-queries on getScreens if we clear it? 
    // Actually the current implementation only parses if empty.
    // We should modify XrandrManager to force reload, but for now let's just create a new one:
    m_manager = XrandrManager(); 
    loadScreens();
}

void MainWindow::applyConfig()
{
    std::vector<ScreenInfo> currentConfig;
    
    // Gather state from scene
    for (QGraphicsItem *item : scene->items()) {
        ScreenItem *screenItem = dynamic_cast<ScreenItem*>(item);
        if (screenItem) {
            ScreenInfo info;
            info.name = screenItem->getName();
            info.width = screenItem->getWidth();
            info.height = screenItem->getHeight();
            info.x = static_cast<int>(screenItem->pos().x() * 10);
            info.y = static_cast<int>(screenItem->pos().y() * 10);
            info.active = true;
            info.connected = true;
            currentConfig.push_back(info);
        }
    }
    
    QString cmd = m_manager.generateCommand(currentConfig);
    qDebug() << "Applying command:" << cmd;
    
    // Execute
    int result = system(cmd.toStdString().c_str());
    if (result == 0) {
        QMessageBox::information(this, "Horizon", "Configuration Applied Successfully!");
    } else {
        QMessageBox::critical(this, "Horizon", "Failed to apply configuration.");
    }
}

void MainWindow::saveConfig()
{
    std::vector<ScreenInfo> currentConfig;
    for (QGraphicsItem *item : scene->items()) {
        ScreenItem *screenItem = dynamic_cast<ScreenItem*>(item);
        if (screenItem) {
            ScreenInfo info;
            info.name = screenItem->getName();
            info.width = screenItem->getWidth();
            info.height = screenItem->getHeight();
            info.x = static_cast<int>(screenItem->pos().x() * 10);
            info.y = static_cast<int>(screenItem->pos().y() * 10);
            info.active = true;
            info.connected = true;
            currentConfig.push_back(info);
        }
    }
    
    QString cmd = m_manager.generateCommand(currentConfig);

    QString fileName = QFileDialog::getSaveFileName(this, "Save Script", "layout.sh", "Shell Script (*.sh)");
    if (!fileName.isEmpty()) {
        QFile file(fileName);
        if (file.open(QIODevice::WriteOnly | QIODevice::Text)) {
            QTextStream out(&file);
            out << "#!/bin/sh\n# Generated by Horizon\n";
            out << cmd << "\n";
            file.close();
            
            // Make executable
            QFile::setPermissions(fileName, QFile::ReadOwner | QFile::WriteOwner | QFile::ExeOwner | QFile::ReadGroup | QFile::ReadOther);
        }
    }
}
